### ISSUE TITLE
Extension unable to install on Visual Studio Community 2022 (ARM64)

### ISSUE THREAD

**Issue by squabbi** [dracula/visual-studio#40]
I had an issue installing this on my Surface Laptop 7, with the Snapdragon X Plus SoC. Although a fix was merged in #32 the issue still remains. This is the error log:

```
13/09/2024 1:20:51 PM - -------------------------------------------
13/09/2024 1:20:51 PM - Microsoft VSIX Installer
13/09/2024 1:20:51 PM - -------------------------------------------
13/09/2024 1:20:51 PM - Initializing Install...
13/09/2024 1:20:51 PM - Searching for applicable products...
13/09/2024 1:20:52 PM - Found installed product - Visual Studio Community 2022
13/09/2024 1:20:52 PM - Found installed product - Global Location
13/09/2024 1:20:52 PM - Extension Details...
13/09/2024 1:20:52 PM - 	Identifier         : Dracula.6b23b8c5-4c12-4d2a-a157-5799e3e26e3c
13/09/2024 1:20:52 PM - 	Name               : Dracula Official
13/09/2024 1:20:52 PM - 	Author             : Zeno Rocha
13/09/2024 1:20:52 PM - 	Version            : 2.2
13/09/2024 1:20:52 PM - 	Description        : A dark theme for Visual Studio.
13/09/2024 1:20:52 PM - 	Locale             : en-US
13/09/2024 1:20:52 PM - 	MoreInfoURL        : https://draculatheme.com/
13/09/2024 1:20:52 PM - 	InstalledByMSI     : False
13/09/2024 1:20:52 PM - 	SupportedFrameworkVersionRange : [4.5,)
13/09/2024 1:20:52 PM - 	SignatureState     : Unsigned
13/09/2024 1:20:52 PM - 	Supported Products : 
13/09/2024 1:20:52 PM - 		Microsoft.VisualStudio.Community
13/09/2024 1:20:52 PM - 			Version : [17.0,18.0)
13/09/2024 1:20:52 PM - 			ProductArchitecture : amd64
13/09/2024 1:20:52 PM - 	References         : 
13/09/2024 1:20:52 PM - 	Prerequisites      : 
13/09/2024 1:20:52 PM - 		-------------------------------------------------------
13/09/2024 1:20:52 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
13/09/2024 1:20:52 PM - 		Name         : Visual Studio core editor
13/09/2024 1:20:52 PM - 		Version      : [17.0,18.0)
13/09/2024 1:20:52 PM - Signature Details...
13/09/2024 1:20:52 PM - 	Extension is not signed.
13/09/2024 1:20:52 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I went ahead and adjusted the manifest and moved the line where `arm64` was declared above `amd64` and now the installer works. Like so:

```
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0, 18.0)">
      <ProductArchitecture>arm64</ProductArchitecture>
      <ProductArchitecture>amd64</ProductArchitecture>
</InstallationTarget>
```

Although it was closed in #30, perhaps the fix of adding both architectures doesn't work in this way?

**Comment by Taoister39** [comment]
I'm having the same problem.
